sudo: false
language: java
jdk: oraclejdk8
services: mysql

# install dependencies
install: mvn dependency:go-offline -B -V

before_script:
        # initalize empty database and privileges 
        - mysql -uroot -e "CREATE DATABASE stevedb_test_2aa6a783d47d;" -v
        - mysql -uroot -e "GRANT ALL PRIVILEGES ON stevedb_test_2aa6a783d47d.* TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v
        - mysql -uroot -e "GRANT SELECT ON mysql.proc TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v
        # grant super privilege required by MariaDB running with log-bin
        - mysql -uroot -e "GRANT SUPER ON *.* TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v

# start the actual build
script: 
        - mvn -Dmaven.javadoc.skip=true clean package -Ptest -B -V
        - mvn -Dmaven.javadoc.skip=true test -Ptest -B -V
        - java -Djava.net.preferIPv4Stack=true -jar target/steve-*.jar &
        - sleep 30
        - 'grep -C 50 -e "Exception: " ~/logs/steve.log && exit 255 || true'
        - elinks -dump -no-references http://localhost:8080/steve/manager/signin
        - killall java


# coverity_scan settings
#
env:
        global:
        - secure: "e2ou0BHMu9fd2daC9pXhjvkZ3CP3XTaYWSIehM4JDWxnVAn1jJayiQOpWoNKeD+RJV24ND1I2WvjQGqu6HVV+CkVZ8kHVCvb7fQHbM4P8UKaMFts8KR1gIiAYc7ja+C/jLnXVTofrhUTinOdhFs1lTONhGa4g/+nWq/6KXXP52/WKsKPgNKOvOzhlJf2QTprOkQVr4tIhUd3K9lf6qORkOIwpcfmQpFfccbHPzoIxGpke+a0Q5+H5/o3gNhOe7w31wBaX90OzfYRA5WyjfbDmI2tjkELQuvitR/DePRK0sLfRKfdfBRD/20pEbG2NzjHCBWQx8CYhDClAuH/sJc3M95qLMCiuNEAcpWzccAMB+At9uMiQfzqNdqTUYPZYQwBQgsPqffG2DyWg6u7eNZu3z0QjLHDxqqOWJa6Hggx9V5nqNNBl0wbrkMjwbWirbtg3yS0i9OLTd8oK64+sYtXPJlBw4Qr+gZplSj/hv6NbcpMKrvOK/BAP+G087m2cVvMpDE9IP7Lo6YXIo5ilSbr4KKs01omvGr1k4eJR2/+esyqanPFuFzhHMRcG0qc0zM+gWlkm/9ID16gMnRQOZTA7UGEeiRpGhVyz87/khg6ajiE2NTxKc1EuHrk18qNulRBc+LjeLLMcS11zTiV6PJ6QkZGheS3+xVp/Nn8DrCC3lE="

addons:
        mariadb: "10.1"
        coverity_scan:
                project:
                        name: "RWTH-i5-IDSG/steve"
                        description: "SteVe - Steckdosenverwaltung"
                notification_email: goekay@dbis.rwth-aachen.de
                build_command_prepend:
                build_command:  "mvn package"
                branch_pattern: master
        apt:
                packages:
                        - elinks

cache:
        directories:
                - $HOME/.m2
