sudo: false
language: java
dist: xenial
jdk: openjdk11
# services: mysql

# install dependencies
install: mvn dependency:go-offline -s .travis-maven-settings.xml -B -V

before_script:
        # initalize empty database and privileges 
        - mysql -uroot -e "CREATE DATABASE stevedb_test_2aa6a783d47d;" -v
        - mysql -uroot -e "GRANT ALL PRIVILEGES ON stevedb_test_2aa6a783d47d.* TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v
        - mysql -uroot -e "GRANT SELECT ON mysql.proc TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v
        # grant super privilege required by MariaDB running with log-bin
        - mysql -uroot -e "GRANT SUPER ON *.* TO 'steve'@'localhost' IDENTIFIED BY 'changeme';" -v

# start the actual build
script: 
        - mvn -s .travis-maven-settings.xml -Dmaven.javadoc.skip=true clean package -Ptest -B -V
        - java -Djava.net.preferIPv4Stack=true -jar target/steve.jar &
        - sleep 30
        - 'grep -C 50 -e "Exception: " ~/logs/steve.log && exit 255 || true'
        - elinks -dump -no-references http://localhost:8080/steve/manager/signin
        - killall java


addons:
        mariadb: "10.3"
        apt:
                packages:
                        - elinks

cache:
        directories:
                - $HOME/.m2
