volumes:
  db-data:
    external: false

services:
  db:
    # Pinning MariaDB to point release 10.4.30 works around the issues with the
    # database migrations seen with 10.4.31 in issue #1212.
    #
    # TODO: Get database migrations to work with the latest point releases of
    # MariaDB 10.4.
    image: mariadb:10.4.30
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-stevedb}"
      MYSQL_USER: "${MYSQL_USER:-steve}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-changeMe!}"
    volumes:
      - db-data:/var/lib/mysql
    # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    restart: unless-stopped
    build: .
    links:
      - "db:mariadb"
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      db:
        condition: service_healthy
