spring:
  application:
    name: steve
  # Database configuration
  #
  datasource:
    url: @db.jdbc.url@
    username: @db.user@
    password: @db.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
    hikari:
      # https://github.com/steve-community/steve/issues/736
      max-lifetime: 580000
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        characterEncoding: utf8
        connectionTimeZone: ${steve.time-zone-id}
        useSSL: true
  flyway:
    table: schema_version

# logback-spring configuration
logging:
  level:
    root: INFO
  appender: FILE

# Jetty configuration
#
server:
  address: 127.0.0.1
  port: 8080
  # Just to be backwards compatible with previous versions, this is set to "steve",
  # since there might be already configured chargepoints expecting the older path.
  # Otherwise, might as well be changed to something else or be left empty.
  #
  servlet:
    context-path: /steve
  compression:
    enabled: true
  ssl:
    enabled: false
    key-store: ${keystore.path}
    key-store-password: ${keystore.password}

steve:
  version: @project.version@
  time-zone-id: UTC
  jooq:
    executive-logging: false
    schema-source: @db.schema@
  # Credentials for Web interface access
  #
  auth:
    username: admin
    password: 1234
  # The header key and value for Web API access using API key authorization.
  # Both must be set for Web APIs to be enabled. Otherwise, we will block all calls.
  #
  web-api:
    header-key: STEVE-API-KEY
    header-value:
  ocpp:
    # When the WebSocket/Json charge point opens more than one WebSocket connection,
    # we need a mechanism/strategy to select one of them for outgoing requests.
    # For allowed values see de.rwth.idsg.steve.ocpp.ws.custom.WsSessionSelectStrategyEnum.
    #
    ws-session-select-strategy: "ALWAYS_LAST"
    # if BootNotification messages arrive (SOAP) or WebSocket connection attempts are made (JSON) from unknown charging
    # stations, we reject these charging stations, because stations with these chargeBoxIds were NOT inserted into database
    # beforehand. by setting this property to true, this behaviour can be modified to automatically insert unknown
    # stations into database and accept their requests.
    #
    # CAUTION: setting this property to true is very dangerous, because we will accept EVERY BootNotification or WebSocket
    # connection attempt from ANY sender as long as the sender knows the URL and sends a valid message.
    #
    auto-register-unknown-stations: false
    # if this field is set, it will take precedence over the default regex we are using in
    # de.rwth.idsg.steve.web.validation.ChargeBoxIdValidator.REGEX to validate the format of the chargeBoxId values
    #
    charge-box-id-validation-regex:
