name: analyze and review code
on: [ push, pull_request ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven

      - name: Check with Maven
        run: mvn -B -V license:check --file pom.xml
  pmd:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run PMD
        uses: pmd/pmd-github-action@v1
        with:
          version: '6.49.0'
          sourcePath: './src/main/java'
          rulesets: './src/main/resources/maven-pmd-plugin-default.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
  checkstyle:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: './src/main/resources/checkstyle.xml'
          workdir: './src/main/java'
          reporter: 'github-pr-check'
          tool_name: 'checkstyle'
